# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a894be0d8b6718f59a40fb7058a842847e5de085a21394d0127c135f848d84e318b132ec0c5e6822b72228dc8cec80c5254ef099cc9835f1b74b127680f70b83

test:
  secret_key_base: 8b41cd370f29c7e4c10fec240f08c457886065a290e3676a32f6543bbd10eb8f1d8362423450d535be9e25ee6fd11a9e8697da97ab1a008c060126255888cd0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
