# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21f19e6d8274ebe78b36d4407d12d192d06693be1cf3e57eaa6ae15da2e98966a4a7109194e445375d40d7efd1538f195ab5ce1a6369705608b8eb8eb7d2637c

test:
  secret_key_base: 3377bfa98aace5755f9faa2b3cdad594a46aee5c8dd4119199aa14b208207d585b74ab19b74cdca5e51da8d66c7a41764f90234fe71ef67fb8d6bbaa4c6067c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
